[package]
name = "file_wizard"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
clap = { version = "4.5.27", features = ["derive"] }
log = "0.4.25"
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.137"
simplelog = "0.12.2"

